name: Build, Lighthouse (móvil) & Deploy to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (minify + version bump)
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  lighthouse:
    name: Lighthouse CI (perfil móvil)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install static server
        run: npm i -g http-server

      - name: Lighthouse CI
        id: lhci
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: .lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          # Sirve dist/ en puerto 4173, SPA mode
          runs: |
            http-server dist -p 4173 -s &

      - name: Publicar reportes como artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ".lighthouseci"

      - name: Resumen en el job
        if: always()
        run: |
          echo "## Lighthouse (perfil móvil)" >> $GITHUB_STEP_SUMMARY
          echo "- **Performance**: ${{ steps.lhci.outputs.performance }} " >> $GITHUB_STEP_SUMMARY
          echo "- **Accessibility**: ${{ steps.lhci.outputs.accessibility }} " >> $GITHUB_STEP_SUMMARY
          echo "- **Best Practices**: ${{ steps.lhci.outputs.bestPractices }} " >> $GITHUB_STEP_SUMMARY
          echo "- **SEO**: ${{ steps.lhci.outputs.seo }} " >> $GITHUB_STEP_SUMMARY
          if [ -f ".lighthouseci/links.txt" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Enlaces a reportes temporales:" >> $GITHUB_STEP_SUMMARY
            cat .lighthouseci/links.txt >> $GITHUB_STEP_SUMMARY
          fi

  deploy:
    needs: [build, lighthouse]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
