name: Build, Lighthouse (móvil) & Deploy to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build (con verificación de íconos)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Verificación de tamaños de íconos y screenshots (falla si algo no coincide)
      - name: Verify PWA icons and screenshots
        run: |
          sudo apt-get update >/dev/null
          sudo apt-get install -y imagemagick >/dev/null
          check() { identify -format "%wx%h\n" "$1" | grep -qx "$2" || { echo "::error::Bad size for $1 (want $2)"; exit 1; }; }
          test -f icons/icon-192.png          && check icons/icon-192.png          192x192
          test -f icons/icon-512.png          && check icons/icon-512.png          512x512
          test -f icons/maskable-192.png      && check icons/maskable-192.png      192x192
          test -f icons/maskable-512.png      && check icons/maskable-512.png      512x512
          test -f icons/apple-touch-icon.png  && check icons/apple-touch-icon.png  180x180
          test -f icons/screen-1080x1920.png  && check icons/screen-1080x1920.png  1080x1920
          test -f icons/screen-1920x1080.png  && check icons/screen-1920x1080.png  1920x1080

      # --- Optimización lossless de PNG (reduce peso sin cambiar tamaños/alpha)
      - name: Optimize PNGs (lossless)
        uses: kirillt/oxipng-action@v1
        with:
          paths: icons
          strip: safe
          optimize: 3

      # --- Build estático a dist/
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: node build.mjs

      # --- Publicamos dist como artifact para otros jobs
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
- name: Clean & normalize icons
  run: |
    sudo apt-get update -qq
    sudo apt-get install -y imagemagick -qq
    bash clean-icons.sh

  lighthouse:
    name: Lighthouse CI (perfil móvil)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install static server
        run: npm i -g http-server

      - name: Lighthouse CI
        id: lhci
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: .lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: |
            http-server dist -p 4173 -s &

      - name: Publicar reportes como artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ".lighthouseci"

      - name: Resumen en el job
        if: always()
        run: |
          echo "## Lighthouse (perfil móvil)" >> $GITHUB_STEP_SUMMARY
          echo "- **Performance**: ${{ steps.lhci.outputs.performance }} " >> $GITHUB_STEP_SUMMARY
          echo "- **Accessibility**: ${{ steps.lhci.outputs.accessibility }} " >> $GITHUB_STEP_SUMMARY
          echo "- **Best Practices**: ${{ steps.lhci.outputs.bestPractices }} " >> $GITHUB_STEP_SUMMARY
          echo "- **SEO**: ${{ steps.lhci.outputs.seo }} " >> $GITHUB_STEP_SUMMARY
          if [ -f ".lighthouseci/links.txt" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Enlaces a reportes temporales:" >> $GITHUB_STEP_SUMMARY
            cat .lighthouseci/links.txt >> $GITHUB_STEP_SUMMARY
          fi

  deploy:
    name: Deploy to Pages
    needs: [build, lighthouse]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
